### ISSUE TITLE
Add ability to change configuration at runtime

### ISSUE THREAD

**Issue by jseminck** [lrferreiro/flutter_flavor#8]
Hello, we recently started using this package and it's working great. Thanks for the effort on it. However, we have a use-case that is currently not implemented and I was wondering if there is a specific reason for that or if we can add the code to make that work. I can help with the PR if you agree on the necessary changes.

What we want to do is to be able to change the configuration at run time. This is currently not possible because of the `?==` operator that is used here: https://github.com/lrferreiro/flutter_flavor/blob/master/lib/src/flavor_config.dart#L37

Was that added on purpose?

Otherwise, I would propose to add some kind of `reset()` or `clear()` function which resets the `_instance` and then allows to overwrite the configuration with new values.

**Comment by lrferreiro** [comment]
Sorry, it's like this on purpose, because I don't think it's necessary to restart the _instance, in any case you can restart the variables, but not the most. If you need any adjustments in the Banner, this allows you to specify the same attributes. Anyway, we can look at that use case to see if it is really worth having a reset () or clear (). Thanks for using the package.
